# Stage 1 - Build

FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY Calculator.java .

RUN javac -d /app/package Calculator.java

RUN jar cfe /app/app.jar Calculator -C /app/package .


# Stage 2 - Runtime

FROM gcr.io/distroless/java21-debian13

WORKDIR /app

COPY --from=builder /app/app.jar .

ENTRYPOINT ["java","-jar","app.jar"]

