# Stage 1 - Build

FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY . /app

RUN javac Hello.java


# Stage 2 - Runtime

FROM gcr.io/distroless/java21-debian13

WORKDIR /app

COPY --from=builder /app/Hello.class .

ENTRYPOINT ["java"]

CMD ["Hello"]
