# Stage 1 - Build

FROM eclipse-temurin:21-jdk-alpine AS builder

WORKDIR /app

COPY Calculator.java .

RUN javac Calculator.java 


# Stage 2 - Runtime

FROM gcr.io/distroless/java21-debian13

WORKDIR /app

COPY --from=builder /app/Calculator.class .

ENTRYPOINT ["java"]

CMD ["Calculator"]
