# Stage 1 - Builder

FROM  maven:3.9.9-eclipse-temurin-11 AS builder

WORKDIR /app

COPY . .

RUN mvn clean package

# Stage 2 - Runtime

FROM gcr.io/distroless/java11-debian11

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

CMD ["app.jar"]

